"""Guard the observable error-presentation behaviour of the Hades II backend.

#204 replaced seven mapping tables with one declarative registry. The refactor
is only acceptable if a player's error message never silently becomes a
different sentence, so this test pins the observable outcome: for every message
the module claims to recognise, the same key and the same arguments.

The snapshot in `error_presentation_snapshot.json` is generated by
`error_presentation_behaviour.py`, which probes the public surface only. That
matters: an earlier guard read the mapping tables by name, so it would have
passed a refactor that broke every single mapping.

Regenerate deliberately, and only when a change to the player-visible mapping is
intended:

    python3 tests/error_presentation_behaviour.py \\
        --out tests/error_presentation_snapshot.json
"""
from __future__ import annotations

import importlib.util
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "tests/error_presentation_snapshot.json"

sys.path.insert(0, str(ROOT / "Backend"))


def _load_behaviour_module():
    path = ROOT / "tests/error_presentation_behaviour.py"
    spec = importlib.util.spec_from_file_location("error_presentation_behaviour", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_every_declared_message_maps_to_the_pinned_key_and_arguments():
    from games.hades2 import error_presentation as error_presentation

    expected = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    problems = []

    for message, want in expected["direct"].items():
        key, arguments = error_presentation.presentation_for(message)
        got = {"key": key, "arguments": list(arguments)}
        if got != want:
            problems.append(f"{message!r}\n    was {want}\n    now {got}")

    if problems:
        raise AssertionError(
            "the error presentation changed, so a player's message moved:\n  "
            + "\n  ".join(problems)
        )


def test_the_snapshot_covers_the_whole_registry():
    """A snapshot that silently drops rules would pass while mappings rot.

    The snapshot is generated from the registry, so a rule added without
    regenerating it would be unpoliced. Requiring the counts to agree means the
    snapshot cannot quietly fall behind the thing it measures.
    """
    from games.hades2 import error_presentation as error_presentation

    expected = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    registry = getattr(error_presentation, "REGISTRY", None)
    if registry is None:
        return  # pre-registry layout; the mapping test above still applies

    behaviour = _load_behaviour_module()
    live = behaviour.snapshot()
    for section in ("direct", "runtime"):
        if live[section] == expected[section]:
            continue
        missing = set(expected[section]) - set(live[section])
        extra = set(live[section]) - set(expected[section])
        changed = [m for m in set(live[section]) & set(expected[section])
                   if live[section][m] != expected[section][m]]
        raise AssertionError(
            f"the snapshot no longer describes the module {section} behaviour. "
            f"missing={sorted(missing)[:4]} extra={sorted(extra)[:4]} "
            f"changed={sorted(changed)[:4]}. "
            "Regenerate with error_presentation_behaviour.py --out if the change "
            "is intended."
        )
    for field in ("fallback_key", "runtime_commands"):
        if live[field] != expected[field]:
            raise AssertionError(
                f"the snapshot no longer describes {field}: "
                f"was {expected[field]!r}, now {live[field]!r}"
            )


def test_the_registry_has_no_unreachable_or_invalid_rules():
    from games.hades2 import error_presentation as error_presentation

    registry = getattr(error_presentation, "REGISTRY", None)
    if registry is None:
        return

    problems = error_presentation.check_registry(registry)
    if problems:
        raise AssertionError("the registry is structurally unsound:\n  " + "\n  ".join(problems))

    shadowed = error_presentation._unreachable(registry)
    if shadowed:
        detail = "; ".join(f"rule {index} is shadowed by {prefix!r}" for index, prefix in shadowed)
        raise AssertionError(f"a registry rule can never fire: {detail}")


def test_each_overlapping_family_still_has_a_genuine_contest():
    """The cross-shape guard must not become decoration.

    The previous check was one global floor, `MIN_SHAPE_COLLISIONS = 2`, and it
    never fired on the regression it was written for: deleting the space from a
    prefix value left 96 collisions from the prefix-vs-delimited family, so the
    global count stayed at 96 while the two families that actually depended on
    that space fell to zero. A single number cannot work -- the delimited family
    alone is 96 -- so each family needs its own floor.
    """
    from games.hades2 import error_presentation as error_presentation

    behaviour = _load_behaviour_module()
    rules = behaviour.ep.REGISTRY
    probes, _ = behaviour._cross_shape_probes(rules)
    families = behaviour._genuine_contests_by_family(rules, probes)

    problems = []
    for name, floor in sorted(behaviour.MIN_GENUINE_CONTEST_FLOORS.items()):
        got = families.get(name, 0)
        if got < floor:
            problems.append(f"  {name}: {got} genuine contest(s), floor is {floor}")
    if problems:
        raise AssertionError(
            "an overlapping shape family lost its contests, so the cross-shape\n"
            "probes for it can no longer detect a dispatch-order change:\n"
            + "\n".join(problems))


def main():
    test_every_declared_message_maps_to_the_pinned_key_and_arguments()
    test_the_snapshot_covers_the_whole_registry()
    test_the_registry_has_no_unreachable_or_invalid_rules()
    test_each_overlapping_family_still_has_a_genuine_contest()
    print("error_presentation_behaviour_ok")


if __name__ == "__main__":
    main()
