"""Finite timeout components used by Hades II aggregate host watchdogs.

Update the maximum subprocess counts whenever prepare/restore add another
bounded command. The count is the audited longest branch, not the number of
commands in a typical run.
"""

SUBPROCESS_TIMEOUT_SECONDS = 30
PREPARATION_MAX_SUBPROCESS_CALLS = 16
RESTORE_MAX_SUBPROCESS_CALLS = 6
PROCESS_QUERY_TIMEOUT_SECONDS = 5

LLDB_DISCOVERY_TIMEOUT_SECONDS = 5
LLDB_PYTHON_TIMEOUT_SECONDS = 8
EXPORT_REVEAL_TIMEOUT_SECONDS = 10

LUA_BOUNDARY_TIMEOUT_SECONDS = 3
LUA_EXPRESSION_TIMEOUT_SECONDS = 2
LUA_CLEANUP_TIMEOUT_SECONDS = 3

POST_PREPARATION_SCAN_BUDGET_SECONDS = (
    SUBPROCESS_TIMEOUT_SECONDS + PROCESS_QUERY_TIMEOUT_SECONDS
)
PREPARATION_OPERATION_BUDGET_SECONDS = (
    PREPARATION_MAX_SUBPROCESS_CALLS * SUBPROCESS_TIMEOUT_SECONDS
    + POST_PREPARATION_SCAN_BUDGET_SECONDS
)
RESTORE_OPERATION_BUDGET_SECONDS = (
    RESTORE_MAX_SUBPROCESS_CALLS * SUBPROCESS_TIMEOUT_SECONDS
    + SUBPROCESS_TIMEOUT_SECONDS
    + PROCESS_QUERY_TIMEOUT_SECONDS
)
STATUS_CHECK_BUDGET_SECONDS = 2 * (
    LUA_BOUNDARY_TIMEOUT_SECONDS
    + LUA_EXPRESSION_TIMEOUT_SECONDS
    + 2 * LUA_CLEANUP_TIMEOUT_SECONDS
)
DIAGNOSTICS_OPERATION_BUDGET_SECONDS = (
    SUBPROCESS_TIMEOUT_SECONDS
    + STATUS_CHECK_BUDGET_SECONDS
    + LLDB_DISCOVERY_TIMEOUT_SECONDS
    + LLDB_PYTHON_TIMEOUT_SECONDS
)
EXPORT_DIAGNOSTICS_OPERATION_BUDGET_SECONDS = (
    DIAGNOSTICS_OPERATION_BUDGET_SECONDS + EXPORT_REVEAL_TIMEOUT_SECONDS
)
